import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from "next/link";

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>Laboratoire Next.js!</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1>Laboratoire Next.js!</h1>
        <Link href="/blog/posts">
          <a>Blog</a>
        </Link>
      </main>
    </div>
  );
}
